### ISSUE TITLE
v1.18 hangs with black screen Android 5.0

### ISSUE THREAD

**Issue by ELynx** [pompobit/ScanGO#8]
Hi,
Phone is Samsung Note 3 Android 5.0.0.
After server selection app hangs with black screen, after some time OS prompts to stop or kill.
Here is something I see in logcat

```
09-14 12:01:17.975 E/list json(25495): {"activeProfile":"NO_FILTERS","profile_list":{"no commons":{"attributes_":{"fPokemon":{"103":true,"37":true,"71":true,"118":true,"97":true,"23":true,"54":true,"94":true,"55":true,"17":true,"127":true,"123":true,"144":true,"64":true,"148":true,"84":false,"49":true,"67":true,"30":true,"145":true,"120":true,"3":true,"57":true,"109":true,"61":true,"59":true,"142":true,"93":true,"86":true,"81":true,"9":true,"40":true,"24":true,"96":true,"102":true,"63":true,"134":true,"68":true,"45":true,"115":true,"80":true,"28":true,"128":true,"1":true,"149":true,"15":true,"117":true,"56":true,"87":true,"26":true,"116":true,"41":false,"146":true,"25":true,"60":true,"58":true,"46":true,"14":true,"20":true,"143":true,"130":true,"22":true,"5":true,"78":true,"135":true,"4":true,"34":true,"76":true,"132":true,"136":true,"99":true,"141":true,"106":true,"39":true,"85":true,"35":true,"150":true,"11":true,"147":true,"101":true,"72":true,"151":true,"113":true,"53":true,"36":true,"125":true,"111":true,"82":true,"95":true,"90":true,"42":true,"52":true,"21":false,"83":true,"7":true,"2":true,"29":true,"13":false,"122":true,"19":false,"47":true,"43":true,"48":true,"27":true,"104":true,"70":true,"119":true,"92":true,"105":true,"32":true,"38":true,"129":true,"31":true,"12":true,"139":true,"137":true,"114":true,"66":true,"140":true,"79":true,"110":true,"33":true,"91":true,"88":true,"62":true,"50":true,"6":true,"108":true,"98":true,"112":true,"126":true,"131":true,"51":true,"16":false,"75":true,"124":true,"8":true,"44":true,"121":true,"69":false,"65":true,"77":true,"18":true,"133":true,"73":true,"89":true,"138":true,"107":true,"100":true,"74":true,"10":false},"name":"no commons"}}}}
09-14 12:01:17.975 D/AndroidRuntime(25495): Shutting down VM
09-14 12:01:17.975 E/strana exception presa(25495): MainActivity di seguito lo stacktrace
09-14 12:01:17.975 W/System.err(25495): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
09-14 12:01:17.985 W/System.err(25495):     at com.acatch.pompomon.scango.af.a(Unknown Source)
09-14 12:01:17.985 W/System.err(25495):     at com.acatch.pompomon.scango.d.e.onActivityCreated(Unknown Source)
09-14 12:01:17.985 W/System.err(25495):     at android.support.v4.app.Fragment.performActivityCreated(Unknown Source)
09-14 12:01:17.985 W/System.err(25495):     at android.support.v4.app.am.a(Unknown Source)
09-14 12:01:17.985 W/System.err(25495):     at android.support.v4.app.am.a(Unknown Source)
09-14 12:01:17.985 W/System.err(25495):     at android.support.v4.app.n.run(Unknown Source)
09-14 12:01:17.985 W/System.err(25495):     at android.support.v4.app.am.b(Unknown Source)
09-14 12:01:17.985 W/System.err(25495):     at android.support.v4.app.n.d(Unknown Source)
09-14 12:01:17.985 W/System.err(25495):     at android.support.v4.app.ax.b(Unknown Source)
09-14 12:01:17.985 W/System.err(25495):     at android.support.v4.view.ViewPager.a(Unknown Source)
09-14 12:01:17.985 W/System.err(25495):     at android.support.v4.view.ViewPager.c(Unknown Source)
09-14 12:01:17.985 W/System.err(25495):     at android.support.v4.view.ViewPager.onMeasure(Unknown Source)
09-14 12:01:17.985 W/System.err(25495):     at android.view.View.measure(View.java:18563)
09-14 12:01:17.985 W/System.err(25495):     at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
09-14 12:01:17.985 W/System.err(25495):     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
09-14 12:01:17.985 W/System.err(25495):     at android.view.View.measure(View.java:18563)
09-14 12:01:17.985 W/System.err(25495):     at android.support.v4.widget.DrawerLayout.onMeasure(Unknown Source)
09-14 12:01:17.985 W/System.err(25495):     at android.view.View.measure(View.java:18563)
09-14 12:01:17.985 W/System.err(25495):     at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
09-14 12:01:17.985 W/System.err(25495):     at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
09-14 12:01:17.985 W/System.err(25495):     at android.view.View.measure(View.java:18563)
09-14 12:01:17.985 W/System.err(25495):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
09-14 12:01:17.985 W/System.err(25495):     at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
09-14 12:01:17.985 W/System.err(25495):     at android.support.v7.widget.ContentFrameLayout.onMeasure(Unknown Source)
09-14 12:01:17.985 W/System.err(25495):     at android.view.View.measure(View.java:18563)
09-14 12:01:17.985 W/System.err(25495):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
09-14 12:01:17.985 W/System.err(25495):     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
09-14 12:01:17.985 W/System.err(25495):     at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
09-14 12:01:17.985 W/System.err(25495):     at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
09-14 12:01:17.985 W/System.err(25495):     at android.view.View.measure(View.java:18563)
09-14 12:01:17.985 W/System.err(25495):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
09-14 12:01:17.985 W/System.err(25495):     at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
09-14 12:01:17.985 W/System.err(25495):     at android.view.View.measure(View.java:18563)
09-14 12:01:17.985 W/System.err(25495):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
09-14 12:01:17.985 W/System.err(25495):     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
09-14 12:01:17.985 W/System.err(25495):     at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
09-14 12:01:17.985 W/System.err(25495):     at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
09-14 12:01:17.985 W/System.err(25495):     at android.view.View.measure(View.java:18563)
09-14 12:01:17.985 W/System.err(25495):     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5827)
09-14 12:01:17.985 W/System.err(25495):     at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
09-14 12:01:17.985 W/System.err(25495):     at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2888)
09-14 12:01:17.985 W/System.err(25495):     at android.view.View.measure(View.java:18563)
09-14 12:01:17.985 W/System.err(25495):     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2248)
09-14 12:01:17.985 W/System.err(25495):     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1306)
09-14 12:01:17.985 W/System.err(25495):     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1548)
09-14 12:01:17.985 W/System.err(25495):     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
09-14 12:01:17.985 W/System.err(25495):     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6642)
09-14 12:01:17.985 W/System.err(25495):     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
09-14 12:01:17.985 W/System.err(25495):     at android.view.Choreographer.doCallbacks(Choreographer.java:590)
09-14 12:01:17.985 W/System.err(25495):     at android.view.Choreographer.doFrame(Choreographer.java:560)
09-14 12:01:17.985 W/System.err(25495):     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
09-14 12:01:17.985 W/System.err(25495):     at android.os.Handler.handleCallback(Handler.java:739)
09-14 12:01:17.985 W/System.err(25495):     at android.os.Handler.dispatchMessage(Handler.java:95)
09-14 12:01:17.985 W/System.err(25495):     at android.os.Looper.loop(Looper.java:145)
09-14 12:01:17.985 W/System.err(25495):     at android.app.ActivityThread.main(ActivityThread.java:5938)
09-14 12:01:17.985 W/System.err(25495):     at java.lang.reflect.Method.invoke(Native Method)
09-14 12:01:17.985 W/System.err(25495):     at java.lang.reflect.Method.invoke(Method.java:372)
09-14 12:01:17.985 W/System.err(25495):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
09-14 12:01:17.985 W/System.err(25495):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
09-14 12:01:18.595 D/SkiplaggedClient(25495): risponde
09-14 12:01:18.595 E/SkiplaggedClient(25495): risposta corretta
```

Since class names are obfuscated this might not be of great help, but never the less.

Later app has another exception, most probably related to fact that it tries to start threads during hang/shut down

```
09-14 12:01:19.395 E/strana exception presa(25495): MainActivity di seguito lo stacktrace
09-14 12:01:19.395 W/System.err(25495): java.lang.InternalError: Thread starting during runtime shutdown
09-14 12:01:19.395 W/System.err(25495):     at java.lang.Thread.nativeCreate(Native Method)
09-14 12:01:19.395 W/System.err(25495):     at java.lang.Thread.start(Thread.java:1063)
09-14 12:01:19.395 W/System.err(25495):     at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)
09-14 12:01:19.395 W/System.err(25495):     at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:988)
09-14 12:01:19.395 W/System.err(25495):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
09-14 12:01:19.395 W/System.err(25495):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
09-14 12:01:19.395 W/System.err(25495):     at java.lang.Thread.run(Thread.java:818)
```

**Comment by pompobit** [comment]
Thank you for report, I did a mess with apks, you can try again now, it should be fixed

**Comment by ELynx** [comment]
@pompobit 
Reloaded v1.18, everything works now. Scan finds no 'mons around me, even when I see them. But I know, this is scanning server issues, not app.

App itself is really great, I love scanning visualization. May be make donated version that will remove ads? Or this is not possible to do without google store release?

**Comment by ELynx** [comment]
OK better discuss on reddir, not Issues. Issue is 100% solved :)
